sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm test -- --coverage

after_success:
  - docker build -t filip505/multi-client ./client
  - docker build -t filip505/multi-nginx ./nginx
  - docker build -t filip505/multi-server ./server
  - docker build -t filip505/multi-worker ./worker
  # Log in to the docke CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  # Take those images and push them to docker hub

  - docker push filip505/multi-client
  - docker push filip505/multi-client
  - docker push filip505/multi-client
  - docker push filip505/multi-client
  
deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-eu-west-1-735494447185"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
